#!/bin/bash
source $HOME/.bash_func
exec < /dev/tty

name=`coalesce $1 'origin'`

git config --get remote.${name}.url > /dev/null 2>&1
if [ $? -eq 0 ]; then
  url=`git config --get remote.${name}.url`
  protocol=`git_url_parse ${url} 1`
  base_url=`git_url_parse ${url} 2`
  user=`git_url_parse ${url} 4`
  repo=`git_url_parse ${url} 5`
  ssh_url="git@${base_url}:${user}/${repo}"
  if ask "convert remote $name: $url to ~~~> $ssh_url"; then
    git remote set-url $name $ssh_url
  fi
else
  echo "${RED}ERROR: remote ${name} not found"
fi
